### ISSUE TITLE
Feedback for “useECharts”

### ISSUE THREAD

**Issue by BH-M87** [kbox-labs/react-echarts#10]
![CleanShot 2023-12-07 at 11 56 27@2x](https://github.com/kbox-labs/react-echarts/assets/16903266/bd201673-0029-4627-bf9f-27ba26e42553)

Met a problem, if use typescript, the type of EChartsProps is any.

**Comment by BH-M87** [comment]
import { SetOptionOpts, EChartOption } from 'echarts';

 it seems like there is an error here.

shoud be `EChartsOption`, not `EChartOption`

**Comment by hugocxl** [comment]
@BH-M87 hi, can you check your version? This type is available from `v1.0.0`

**Comment by BH-M87** [comment]
![CleanShot 2023-12-08 at 15 47 20@2x](https://github.com/kbox-labs/react-echarts/assets/16903266/8d83f331-6dda-4db8-9502-a5d8a0732798)

Here is my version, it's 1.0.0.
I think we met a problem with spelling mistake. The correct word should be `EChartsOption `.

![CleanShot 2023-12-08 at 15 49 14@2x](https://github.com/kbox-labs/react-echarts/assets/16903266/4943d13b-e857-4808-a84d-3b037195330d)

**Comment by hugocxl** [comment]
Hi @BH-M87, sorry I just want to make sure I am understanding your issue here. 
You're importing `EChartProps` from the lib but it appears to be `any`, is that correct?

I am checking in a new project, and I'm getting the correct typing:
<img width="1085" alt="Screenshot 2023-12-08 at 11 54 02" src="https://github.com/kbox-labs/react-echarts/assets/36138779/65831589-e2e2-4b90-a91f-f828364a3ae7">

Could you give me more details? I think I am not getting your issue completely.
Thanks

**Comment by BH-M87** [comment]
From your screenshot, I saw `EChartsOption`，this is correct.

![CleanShot 2023-12-11 at 10 33 31@2x](https://github.com/kbox-labs/react-echarts/assets/16903266/6dad2416-5787-487c-b1c8-5c48b2971277)

I believe this issue is fixed. I will install the latest version `v1.0.1` to  check whether it is worked correctly.

**Comment by BH-M87** [comment]
Another problem is if add `ContainerProps`, the type check may be loose if pass an inexistent props into `<Echart />`, there will be no typing error.
![CleanShot 2023-12-11 at 10 44 18@2x](https://github.com/kbox-labs/react-echarts/assets/16903266/59a714aa-f45f-4da9-ac68-cbeea05d3e9b)

**Comment by hugocxl** [comment]
@BH-M87 yes that is expected, as it is the normal behaviour in React (non-native html attributes are serialized and passed down to the DOM node).

In case you need to narrow down the props, I recommend you [this example from the docs](https://kbox-labs.github.io/react-echarts/examples#creating-your-own-echart--component), where you can create you own `EChart` component and control the typing as needed.
