### ISSUE TITLE
Feedback for “EChart”

### ISSUE THREAD

**Issue by telfDavid** [kbox-labs/react-echarts#12]
I need to use the function `registerMap` in order to set a svg in the echart's GEO/Map charts, but I don't find it anywhere in the docs, is this option possible??

what I'm trying to do:
https://echarts.apache.org/examples/en/editor.html?c=geo-seatmap-flight&theme=dark
<img width="565" alt="image" src="https://github.com/kbox-labs/react-echarts/assets/125882026/c02cbaae-cf41-4b15-ada6-b04f71a1e7a3">

**Comment by hugocxl** [comment]
@telfDavid that functionality is part of echarts so you can call it as you need in your project.

Please mind that all not-react related code is not part of this lib and must be accessed through "echarts" itself.

```tsx
import { registerMap } from "echarts"

registerMap(...)

export function App() {
    // ...your code
}
```

Hope that helps
